KC-6601 #comment Adding the PHPMD ruleset

diff --git a/api/qualitycontrol/pre-commit b/api/qualitycontrol/pre-commit
--- a/api/qualitycontrol/pre-commit
+++ b/api/qualitycontrol/pre-commit
@@ -2,7 +2,7 @@
 
 PROJECT=`php -r "echo dirname(dirname(dirname(dirname(dirname(realpath('$0'))))));"`
 FLIPIT_APPLICATION="flipit_application"
-API="/api"
+API="api"
 STAGED_FILES_CMD=`git diff --cached --name-only --diff-filter=ACMR HEAD | grep \\\\.php`
 
 # Determine if a file list is passed
@@ -30,7 +30,15 @@ done
 if [ "$FILES" != "" ]
 then
 	echo "Running Code Sniffer..."
-	$PROJECT/$FLIPIT_APPLICATION/$API/vendor/bin/phpcs --standard=$PROJECT/$FLIPIT_APPLICATION/$API/PhpCS/ruleset.xml --encoding=utf-8  -n -p $FILES
+	$PROJECT/$FLIPIT_APPLICATION/$API/vendor/bin/phpcs --standard=$PROJECT/$FLIPIT_APPLICATION/$API/qualitycontrol/PhpCS/ruleset.xml --encoding=utf-8  -n -p $FILES
+	if [ $? != 0 ]
+	then
+		echo "Fix the error before commit."
+		exit 1
+	fi
+
+	echo "Running PHPMD..."
+	$PROJECT/$FLIPIT_APPLICATION/$API/vendor/bin/phpmd $FILES text $PROJECT/$FLIPIT_APPLICATION/$API/qualitycontrol/PhpMD/ruleset.xml
 	if [ $? != 0 ]
 	then
 		echo "Fix the error before commit."
